# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Diffenece.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import AllFunctions,hashlib,json
from docxtpl import DocxTemplate


class Ui_Form(object):
    different_docs=AllFunctions.load_Different_docks()
    DataToTable=AllFunctions.load_DataToTable()
    HeshData=AllFunctions.load_HeshData()
    Ndoc=0

    def __init__(self):
        super().__init__()
        self.window=QtWidgets.QMainWindow()
        self.setupUi(self.window)


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(881, 605)
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(310, 0, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("\n"
"border: 3px solid black;\n"
"border-left: 0px;\n"
"border-right: 0px;\n"
"border-top: 0px;")
        self.label_16.setObjectName("label_16")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 50, 811, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("padding: 1 5 0 0;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout.addWidget(self.lineEdit_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("padding: 1 5 0 0;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout.addWidget(self.dateEdit_2)
        self.dateEdit_3 = QtWidgets.QDateEdit(Form)
        self.dateEdit_3.setGeometry(QtCore.QRect(129, 170, 331, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.dateEdit_3.setFont(font)
        self.dateEdit_3.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_3.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(129, 138, 331, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(14, 480, 113, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("padding: 1 5 0 0;")
        self.label_9.setObjectName("label_9")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(10, 231, 113, 235))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("padding: 1 5 0 0;")
        self.label_17.setObjectName("label_17")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(466, 138, 56, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("padding: 1 5 0 0;")
        self.label_10.setObjectName("label_10")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(10, 169, 113, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("padding: 1 5 0 0;")
        self.label_18.setObjectName("label_18")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(129, 200, 730, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(466, 169, 56, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("padding: 1 5 0 0;")
        self.label_19.setObjectName("label_19")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(532, 480, 331, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(133, 480, 331, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(470, 480, 56, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("padding: 1 5 0 0;")
        self.label_20.setObjectName("label_20")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(129, 231, 730, 241))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(10, 138, 113, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("padding: 1 5 0 0;")
        self.label_21.setObjectName("label_21")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(528, 169, 331, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(528, 138, 331, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setStyleSheet("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(10, 200, 113, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("padding: 1 5 0 0;")
        self.label_22.setObjectName("label_22")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 530, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 530, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)



        self.pushButton.clicked.connect(self.add_new_document)
        try:
            self.Fill_document()
        except:
            pass

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_16.setText(_translate("Form", "Редактирование документа"))
        self.label_8.setText(_translate("Form", "Учетный №"))
        self.label_11.setText(_translate("Form", "Дата регистрации"))
        self.dateEdit_2.setDisplayFormat(_translate("Form", "«dd» MM yyyy г."))
        self.dateEdit_3.setDisplayFormat(_translate("Form", "«dd» MM yyyy г."))
        self.label_9.setText(_translate("Form", "Звание"))
        self.label_17.setText(_translate("Form", "Содержание"))
        self.label_10.setText(_translate("Form", "Номер"))
        self.label_18.setText(_translate("Form", "Дата"))
        self.label_19.setText(_translate("Form", "Город"))
        self.label_20.setText(_translate("Form", "ФИО"))
        self.label_21.setText(_translate("Form", "Кто подписал"))
        self.label_22.setText(_translate("Form", "Наименование"))
        self.pushButton.setText(_translate("Form", "Сохранить изменения"))
        self.pushButton_2.setText(_translate("Form", "Отмена"))

    def Fill_document(self, Ndoc):
        self.Ndoc = Ndoc


        self.lineEdit_9.setText(self.different_docs[self.Ndoc][-1][1])#who
        self.lineEdit_14.setText(self.different_docs[self.Ndoc][-1][2])#numder


        data_text = self.different_docs[self.Ndoc][-1][3]
        date_format = '«dd» MM yyyy г.'
        self.dateEdit_3.setDate(QtCore.QDate.fromString(data_text, date_format))



        self.lineEdit_13.setText(self.different_docs[self.Ndoc][-1][4])#sity
        self.lineEdit_10.setText(self.different_docs[self.Ndoc][-1][5])#name_of_document
        self.textEdit_2.setText(self.different_docs[self.Ndoc][-1][6])#text_of_doc
        self.lineEdit_12.setText(self.different_docs[self.Ndoc][-1][7])#zvanie
        self.lineEdit_11.setText(self.different_docs[self.Ndoc][-1][8])#FIO



        self.lineEdit_7.setText(str(self.DataToTable[self.Ndoc][0]))
        self.dateEdit_2.setDate(QtCore.QDate.fromString(self.DataToTable[self.Ndoc][3], date_format))



    def add_new_document(self):
        hash_in_t = []
        data_in_t = []
        Ntime = len(self.different_docs[self.Ndoc]) - 1
        Ntime_new = Ntime+1




        # Основной код
        doc = DocxTemplate('Files/Order.docx')
        dictionary = {}
        dictionary['who_a'] = self.lineEdit_9.text()  # self.plus_a()
        dictionary['who'] = self.lineEdit_9.text()
        dictionary['number'] = self.lineEdit_14.text()
        dictionary['date'] = self.dateEdit_3.text()
        dictionary['city'] = self.lineEdit_13.text()
        dictionary['name'] = self.lineEdit_10.text()
        dictionary['context'] = self.textEdit_2.toPlainText()
        dictionary['rank'] = self.lineEdit_12.text()
        dictionary['FIO'] = self.lineEdit_11.text()

        open_text_in_str = ''
        # Создание словаря
        count=0
        for i in dictionary.values():
            open_text_in_str += i  # страка значений открытого текста
            hash_data_of_attributs_before=self.HeshData[self.Ndoc][-1][count]#загружаем предыдущее значение
            hash_data_of_attributs = hashlib.md5(i.encode()+hash_data_of_attributs_before.encode()).hexdigest()  # хэш отдельного атрибута
            hash_in_t.append(hash_data_of_attributs)  # хэш за документ
            data_in_t.append(i)
            count+=1
        # слоавь значений
        self.different_docs[self.Ndoc].append(data_in_t)  # добавление значения открытого текста
        self.HeshData[self.Ndoc].append(hash_in_t)  # добавление значения хэшей документа


        #загрузка предыдущей подписи админа
        last_admin_signature=AllFunctions.load_Admin_signature(self.Ndoc,Ntime)
        last_user_signature=AllFunctions.load_User_signature(self.Ndoc,Ntime)


        # Подписи администратора и пользователя
        admin_key, admin_cert, user = AllFunctions.Load_Admin_key_and_cert()
        signature = AllFunctions.sign_doc(user, open_text_in_str + last_admin_signature.hex(), admin_key, self.Ndoc,Ntime_new)
        user_key, user_cert, user = AllFunctions.Load_User_key_and_cert()
        signature = AllFunctions.sign_doc(user, open_text_in_str + last_user_signature.hex(), user_key, self.Ndoc,Ntime_new)


        AllFunctions.save_HeshData(self.HeshData)
        AllFunctions.save_DataToTable(self.DataToTable)
        AllFunctions.save_Different_docks(self.different_docs)

        doc.render(dictionary)
        doc.save(f'docs/document{self.Ndoc}_{Ntime_new}.docx')
        self.window.close()
