# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doucment.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import AllFunctions


class Ui_Form(object):
    def __init__(self,DiffenceClass):
        super().__init__()
        self.window=QtWidgets.QMainWindow()
        self.setupUi(self.window)
        self.Ndoc = 0
        self.Diffence_Class = DiffenceClass



    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(828, 610)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit = QtWidgets.QTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 50, 831, 501))
        self.plainTextEdit.setStyleSheet("border: 3px solid white;\n"
"border-top-color: rgb(0, 0, 0);\n"
"")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(320, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("border: 2px solid white;\n"
"border-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(300, 570, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(lambda: self.Diffence_Class.Fill_document(self.Ndoc))
        self.pushButton.clicked.connect(lambda: self.Diffence_Class.window.show())

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "Документ"))
        self.pushButton.setText(_translate("Form", "Внести изменения"))

    # def Fill_document(self, namedocument):
    #     pass
    #     # self.plainTextEdit.toPlainText(
    #     #     AllFunctions.convert_docs_to_file(f'docs/document{0}_{0}.docx'))  # f'docs/document{len(self.TableData)}.docx'
    #     #

